CREATE TABLE media (
	id SERIAL PRIMARY KEY,
	url VARCHAR(255) NOT NULL,
	type VARCHAR(50),
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX  idx_media ON media(id);